# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazydlp < Formula
  desc "A TUI for yt-dlp written in Go."
  homepage "https://github.com/ayushsharma74/lazydlp"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ayushsharma74/lazydlp/releases/download/v0.1.3/lazydlp_Darwin_x86_64.tar.gz"
      sha256 "ff3327418bce023aeddddbc0baf33ea495cb8b8fa3dc0c52a8df3974635fe8ad"

      def install
        bin.install "lazydlp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ayushsharma74/lazydlp/releases/download/v0.1.3/lazydlp_Darwin_arm64.tar.gz"
      sha256 "9c94cf046d5b088d2ed6950112496184e041f04d92a320d0cab81913f2567f9a"

      def install
        bin.install "lazydlp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ayushsharma74/lazydlp/releases/download/v0.1.3/lazydlp_Linux_x86_64.tar.gz"
      sha256 "0b62f1532f8fa7e4a6d55cc3ecf61de16684d1588d15a5fc64d54d7b9dee0a1d"
      def install
        bin.install "lazydlp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ayushsharma74/lazydlp/releases/download/v0.1.3/lazydlp_Linux_arm64.tar.gz"
      sha256 "9a752f4188f60c4885a342d7c08e0cada8a695b4fe29cc94ca9126a2a47b82b8"
      def install
        bin.install "lazydlp"
      end
    end
  end
end
