# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazydlp < Formula
  desc "A TUI for yt-dlp written in Go."
  homepage "https://github.com/ayushsharma74/lazydlp"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ayushsharma74/lazydlp/releases/download/v0.1.1/lazydlp_Darwin_x86_64.tar.gz"
      sha256 "f66dcfd4f3b29c44b75aba6a50c10fa7233d27b36aa39acd0822651671874d29"

      def install
        bin.install "lazydlp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ayushsharma74/lazydlp/releases/download/v0.1.1/lazydlp_Darwin_arm64.tar.gz"
      sha256 "95d3a1c505effe29e6042e69713d815d427b56399c0c4bed6737d20fb6c21630"

      def install
        bin.install "lazydlp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ayushsharma74/lazydlp/releases/download/v0.1.1/lazydlp_Linux_x86_64.tar.gz"
      sha256 "a8a655e910489a75989ca8c72057079505355ce3e365ede26b24acee5d685d03"
      def install
        bin.install "lazydlp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ayushsharma74/lazydlp/releases/download/v0.1.1/lazydlp_Linux_arm64.tar.gz"
      sha256 "c74a4352b9b7724ceb32fe187f288f5a08d6cdb4022b77071907bd622af1b9ba"
      def install
        bin.install "lazydlp"
      end
    end
  end
end
