# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portkiller < Formula
  desc "Simple TUI to kill open ports, written in Go."
  homepage "https://github.com/ayushsharma74/portkiller"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ayushsharma74/portkiller/releases/download/v0.0.2/portkiller_Darwin_x86_64.tar.gz"
      sha256 "5660dfde689ffd943db4f2db23a84243264348a7d8cfce8eb1e6364fa2dd44a7"

      def install
        bin.install "portkiller"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ayushsharma74/portkiller/releases/download/v0.0.2/portkiller_Darwin_arm64.tar.gz"
      sha256 "a7ba58a1ad5e1d826d2dd477970cf93a05c54cd0e8714a34fe8217066c4b0484"

      def install
        bin.install "portkiller"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ayushsharma74/portkiller/releases/download/v0.0.2/portkiller_Linux_x86_64.tar.gz"
      sha256 "3ba258b4f7cbd8c5a13d7dca71bdce2ed777b0d518b8328ea4e8072f5347928d"
      def install
        bin.install "portkiller"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ayushsharma74/portkiller/releases/download/v0.0.2/portkiller_Linux_arm64.tar.gz"
      sha256 "a4d092b129a74e9eae3395c8cf4925229f4152d3d9aa00140f69cf79381df0d3"
      def install
        bin.install "portkiller"
      end
    end
  end
end
