# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portkiller < Formula
  desc "Simple TUI to kill open ports, written in go using bubbletea and lipgloss."
  homepage "https://github.com/ayushsharma74/portkiller"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ayushsharma74/portkiller/releases/download/v0.0.1/portkiller_Darwin_x86_64.tar.gz"
      sha256 "43b38acebbef5cdfc17516c7ad02187947cb5957e375484ab3e17a4e89bf5a74"

      def install
        bin.install "portkiller"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ayushsharma74/portkiller/releases/download/v0.0.1/portkiller_Darwin_arm64.tar.gz"
      sha256 "00ca6d7dfd92b823d491f0616538b055574cca13878546e2d827fb34a4537946"

      def install
        bin.install "portkiller"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ayushsharma74/portkiller/releases/download/v0.0.1/portkiller_Linux_x86_64.tar.gz"
      sha256 "a02abafc26d1e71eeb2dd1061cd6772e306c3210730acd2b76214f05a30095c2"
      def install
        bin.install "portkiller"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ayushsharma74/portkiller/releases/download/v0.0.1/portkiller_Linux_arm64.tar.gz"
      sha256 "0b36f369c0cce299ab9cefd8d53c21d5337b315cb81ac9dc914c4d136f459ece"
      def install
        bin.install "portkiller"
      end
    end
  end
end
