# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portkiller < Formula
  desc "Simple TUI to kill open ports, written in Go."
  homepage "https://github.com/ayushsharma74/portkiller"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ayushsharma74/portkiller/releases/download/v0.0.2/portkiller_Darwin_x86_64.tar.gz"
      sha256 "01f3072c4cde60b149a7908da7a8f2f8d54712cfaaf32c15073354116068a1b6"

      def install
        bin.install "portkiller"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ayushsharma74/portkiller/releases/download/v0.0.2/portkiller_Darwin_arm64.tar.gz"
      sha256 "e0999abb2bdce57d6b27aeccc168f96465d0ac41f7c4f2093ec8d0fe0b2788f8"

      def install
        bin.install "portkiller"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ayushsharma74/portkiller/releases/download/v0.0.2/portkiller_Linux_x86_64.tar.gz"
      sha256 "ee371e7befd6f73f37b333a8371a895dabc308a778995907ffe1c1db20142ded"
      def install
        bin.install "portkiller"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ayushsharma74/portkiller/releases/download/v0.0.2/portkiller_Linux_arm64.tar.gz"
      sha256 "52c15b700da60bbff99a82716766ad82785c3c2d9f5a00b8141a247821b7f02c"
      def install
        bin.install "portkiller"
      end
    end
  end
end
